apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: builder
spec:
  selector:
    app.kubernetes.io/name: api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
