version: "3.9"
services:
  ai_framework:
    build:
      context: ./ai_framework
      dockerfile: Dockerfile
    container_name: ai_framework
    ports:
      - "8001:8001"
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:8001,http://127.0.0.1:8001}
      - TRUSTED_HOSTS=${TRUSTED_HOSTS:-*}
    restart: unless-stopped
