version: "3.1"

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "127.0.0.1:5678:5678"  # Bind to localhost only for security
    env_file:
      - .env
    environment:
      - N8N_SECURE_COOKIE=true
      - N8N_LOG_LEVEL=warn
      - N8N_DISABLE_UI=false
    volumes:
      - n8n_data:/home/node/.n8n
    user: "1000:1000"  # Run as non-root user
    networks:
      - n8n_network

volumes:
  n8n_data:
    driver: local

networks:
  n8n_network:
    driver: bridge
    internal: false

