# ruff.toml
line-length = 100
target-version = "py311"

exclude = [
  ".venv",
  "venv",
  "__pycache__",
  "build",
  "dist",
  ".mypy_cache",
  ".pytest_cache"
]

# Enable common, useful rule sets:
select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "I",   # isort (import order)
  "UP",  # pyupgrade
  "B",   # flake8-bugbear
  "SIM", # flake8-simplify
  "PL",  # pylint (subset)
  "PERF",# performance
  "RUF"  # ruff-specific
]

ignore = [
  "E501" # line length handled by formatter
]

[format]
# Ruff formatter style (Black-compatible)
quote-style = "double"
indent-style = "space"
line-ending = "lf"
skip-magic-trailing-comma = false

[lint.isort]
known-first-party = ["backend", "app", "src"]
force-wrap-aliases = true
combine-as-imports = true
