global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api"
    static_configs:
      - targets: ["host.docker.internal:8000"]
  - job_name: "manager"
    static_configs:
      - targets: ["manager:9109"]

rule_files:
  - alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
