name: backend
on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
  pull_request:
    paths:
      - "backend/**"
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: builder
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:7-alpine
        ports: ["6379:6379"]
    env:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@localhost:5432/builder
      REDIS_URL: redis://localhost:6379/0
      SECURE_MODE: true
      INTERNAL_API_KEY: testkey
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          cd backend
          python -m venv .venv
          . .venv/bin/activate
          pip install -U pip
          pip install -r requirements.txt
      - name: Lint and unit tests
        run: |
          cd backend
          . .venv/bin/activate
          python - <<PY
import requests, time
# simple health check of FastAPI app in-process
from app.main import create_app
app = create_app()
print("app created")
PY
      - name: Build API image
        run: |
          docker build -f backend/Dockerfile -t builder-api:ci backend
