name: CI - Full 11-Layer Protection
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: "3.11", cache: "pip" }

      - name: System deps
        run: sudo apt-get update && sudo apt-get install -y lsof curl

      - name: Dependencies (Layer 7)
        run: make deps

      - name: Doctor + Smoke (Layers 1-6: Fortress Gates)
        run: |
          CHECK_FRONTEND=0 scripts/doctor.sh
          cd backend && python scripts/smoke_check.py

      - name: Lint & Format (Layer 8: Code Quality)
        run: |
          make lint-py
          if [ -d "frontend" ]; then make lint-js; fi

      - name: Tests + Coverage (Layer 9: Test Coverage)
        run: make coverage

      - name: Dependency Guardian (Layer 7: Security Audit)
        run: make audit
