name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.12"
  NODE_VERSION: "20"
  API_BASE_URL: "http://127.0.0.1:8000"
  NEXT_PUBLIC_API_BASE_URL: "http://127.0.0.1:8000"
  ALLOWED_ORIGINS: "http://localhost:3000"

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run pytest
        env:
          CI_ENV: "true"
          CI_CLEANUP_TOKEN: ${{ secrets.CI_CLEANUP_TOKEN || 'ci-secret' }}
          ALLOWED_ORIGINS: ${{ env.ALLOWED_ORIGINS }}
        run: |
          PYTHONPATH=backend pytest -q backend/tests

  e2e:
    runs-on: ubuntu-latest
    needs: backend-tests
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Start API (background) and wait for health
        working-directory: backend
        env:
          CI_ENV: "true"
          CI_CLEANUP_TOKEN: ${{ secrets.CI_CLEANUP_TOKEN || 'ci-secret' }}
          DATABASE_URL: sqlite:///./dev-ci.db
          ALLOWED_ORIGINS: ${{ env.ALLOWED_ORIGINS }}
        run: |
          nohup uvicorn app.main:app --host 127.0.0.1 --port 8000 > ../api.log 2>&1 &
          for i in {1..60}; do
            curl -sf ${{ env.API_BASE_URL }}/health && break || sleep 1;
          done

      - name: Install web deps and Playwright
        working-directory: apps/web
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: apps/web
        env:
          API_BASE_URL: ${{ env.API_BASE_URL }}
          NEXT_PUBLIC_API_BASE_URL: ${{ env.API_BASE_URL }}
          CI_ENV: "true"
          CI_CLEANUP_TOKEN: ${{ secrets.CI_CLEANUP_TOKEN || 'ci-secret' }}
        run: |
          npx playwright test --reporter=line

      - name: Upload Playwright test results (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: apps/web/test-results
