name: infra
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "infra/**"
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      - name: fmt & validate
        run: |
          cd infra/terraform
          terraform fmt -check -recursive
          terraform init -backend=false
          terraform validate
      - name: plan (no backend)
        run: |
          cd infra/terraform
          terraform init -backend=false
          terraform plan -var-file=envs/example.auto.tfvars
  apply:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: init
        run: |
          cd infra/terraform
          terraform init -backend=false
      - name: apply
        run: |
          cd infra/terraform
          terraform apply -auto-approve -var-file=envs/example.auto.tfvars
