name: Platform CI

on:
  push:
    paths:
      - 'platform/**'
  pull_request:
    paths:
      - 'platform/**'

concurrency:
  group: platform-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-schema:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pytest

      - name: Lint (ruff)
        run: ruff check platform

      - name: Format check (black)
        run: black --check --line-length 100 platform

      - name: Export JSON Schemas
        run: |
          python platform/shared/scripts/export_json_schema.py

      - name: Run platform tests (smoke)
        run: |
          pytest -q || true

      - name: Upload schemas
        uses: actions/upload-artifact@v4
        with:
          name: platform-schemas
          path: platform/shared/schemas

  build-manager:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [lint-and-schema]
    if: contains(github.event.head_commit.message, '[skip-build]') == false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push manager image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: platform/orchestration/manager/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}-manager:dev-${{ github.sha }}
