name: Security Scans

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Python audit
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -U pip pip-audit safety
          pip-audit -r backend/requirements.txt || true
          safety check -r backend/requirements.txt || true
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: NPM audit
        working-directory: apps/web
        run: |
          npm ci
          npm audit --audit-level=high || true

  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: python, javascript
      - uses: github/codeql-action/analyze@v3

