name: security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scans:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gitleaks (secrets)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-banner --redact --exit-code 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Bandit (Python)
        run: |
          pip install bandit
          bandit -q -r backend/app || true

      - name: OSV-Scanner (deps)
        uses: google/osv-scanner-action@v1
        with:
          scan-args: |-
            --lockfile=apps/web/package-lock.json
            --lockfile=backend/requirements.txt

      - name: Trivy FS scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: .
          format: sarif
          output: trivy-results.sarif

      - name: Upload Trivy SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      - name: Snyk (JS deps)
        if: ${{ secrets.SNYK_TOKEN != '' }}
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --severity-threshold=high

