name: weekly-restore
on:
  schedule:
    - cron: '0 6 * * 1'
jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Placeholder weekly restore drill
        run: echo "Simulated restore; wire S3 creds and scripts/restore_db.sh in prod CI"

