# Example image tags overlay; CI will substitute
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
        - name: api
          image: 123456789012.dkr.ecr.us-west-2.amazonaws.com/builder-api:dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  template:
    spec:
      containers:
        - name: worker
          image: 123456789012.dkr.ecr.us-west-2.amazonaws.com/builder-worker:dev
